AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'bid-calculator

  Sample SAM Template for bid-calculator

  '
Globals:
  Function:
    Timeout: 200
  Api:
    EndpointConfiguration: REGIONAL
    Cors: '''www.clayweidinger.com'''
Resources:
  PitchBidCalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://clayweidinger-lambda-code/144054d39d24138ec0ff1fb7cf6cf4aa
      Handler: pitch.bid.PitchBidCalculatorFuntion::handleRequest
      Runtime: java8
      MemorySize: 128
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /pitch-bid
            Method: get
    Metadata:
      SamResourceId: PitchBidCalculatorFunction
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Pitch Bid function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pitch-bid/
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - PitchBidCalculatorFunction
      - Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - PitchBidCalculatorFunctionRole
      - Arn
